# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bankaccountopening_name'),
        ('services', '0002_auto_20170325_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='accounts.Branch'),
        ),
    ]
