# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
