# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branchreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('star', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('customer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.CustomerService')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
