# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170325_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='due_date',
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.BankAccount'),
            preserve_default=False,
        ),
    ]
