# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170325_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.CustomerService'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.OrderType'),
            preserve_default=False,
        ),
    ]
