# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170324_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='speed_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
