# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankaccountopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountopening',
            name='name',
        ),
    ]
