# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:15
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bankaccountopening_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
