# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170324_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='sort_code',
            field=models.IntegerField(),
        ),
    ]
