# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170324_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_services', to='accounts.Branch'),
        ),
    ]
